# Generated by Django 3.1.4 on 2021-01-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComicsReader', '0002_auto_20210117_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='publication_date',
            field=models.DateField(verbose_name='Дата публикации'),
        ),
    ]
