# Generated by Django 3.1.4 on 2021-01-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComicsReader', '0003_auto_20210118_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='codename',
            field=models.CharField(default='default', max_length=255, verbose_name='Кодовое название'),
            preserve_default=False,
        ),
    ]
