# Generated by Django 3.1.4 on 2021-01-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComicsReader', '0004_comic_codename'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='number',
            field=models.IntegerField(default=1, verbose_name='Номер страницы'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comic',
            name='codename',
            field=models.CharField(max_length=255, unique=True, verbose_name='Кодовое название'),
        ),
    ]
