# Generated by Django 3.1.4 on 2021-01-18 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ComicsReader', '0005_auto_20210118_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='next_issue',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='+', to='ComicsReader.comic'),
        ),
        migrations.AddField(
            model_name='comic',
            name='previous_issue',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='+', to='ComicsReader.comic'),
        ),
    ]
