# Generated by Django 3.1.4 on 2021-01-18 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ComicsReader', '0006_auto_20210118_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='next_issue',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ComicsReader.comic'),
        ),
        migrations.AlterField(
            model_name='comic',
            name='previous_issue',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ComicsReader.comic'),
        ),
    ]
