# Generated by Django 3.1.4 on 2021-01-18 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ComicsReader', '0007_auto_20210118_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comic',
            name='next_issue',
        ),
        migrations.RemoveField(
            model_name='comic',
            name='previous_issue',
        ),
        migrations.AlterField(
            model_name='page',
            name='comic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ComicsReader.comic'),
        ),
    ]
