# Generated by Django 3.1.4 on 2021-01-18 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ComicsReader', '0009_auto_20210118_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='next_issue',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ComicsReader.comic'),
        ),
        migrations.AddField(
            model_name='comic',
            name='previous_issue',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ComicsReader.comic'),
        ),
        migrations.AlterField(
            model_name='page',
            name='comic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ComicsReader.comic'),
        ),
    ]
